### ISSUE TITLE
uhttpc-bench: command not found

### ISSUE THREAD

**Issue by Ortall** [hvr/uhttpc#2]
Hii,
I am trying to use your tool to test my NGINX module, I flowed the installation steps without errors, when I try to run the tool I get "uhttpc-bench: command not found", when I try to install it again I get 
"Resolving dependencies...
All the requested packages are already installed:
uhttpc-0.1.1.0
Use --reinstall if you want to reinstall anyway

I tried to reinstall, but it does not changed the situation

Thanks

**Comment by hvr** [comment]
Did you use `cabal install uhttpc`? if so, the executable gets installed into `${HOME}/.cabal/bin` by default...

**Comment by Ortall** [comment]
I found it, Thanks!!
